version: "3.8"
services:
  web:
    depends_on:
      - redis
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: [ "/wait-for-it.sh", "mariadb:3306", "--", "/go/bin/covidbot-web" ]
    restart: on-failure

  bot:
    depends_on:
      - redis
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    command: ["/wait-for-it.sh", "mariadb:3306", "--", "/go/bin/covidbot-bot"]
    restart: on-failure

  redis:
    image: "redis:alpine"
    restart: on-failure

  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: covid_sim
      MYSQL_USER: covid_sim
      MYSQL_PASSWORD: password
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 15