FROM golang:1.14

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./cmd/covidbot-bot
RUN go install -v ./cmd/covidbot-bot

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD ["/go/bin/covidbot-bot"]